### PR TITLE
Expose data storage port 9160

### PR DESCRIPTION
**Pull request by PVince81**
Required for TUS uploads that talk directly to the data provider

### CODE REVIEW

**Comment by PVince81** [comment]
This makes the call to the data provider go through instead of being stuck until timeout.

However this reveals further issues to be debugged (a 500 error in the PATCH call)

@felixboehm @butonic

**Comment by jnweiger** [comment]
Ah, that is why the uploads fail? :+1:
Testing that extra port with owncloud-client 2.7.x daily: Yes , now the client can upload files! 

Testing that extra port with the Phoenix web ui, I still seem to get 

image

**Review by jnweiger — APPROVED** [review]
solves upload issue with desktop client. 
LGTM.

**Comment by PVince81** [comment]
note, in the future we should look into putting this behind the proxy, see https://github.com/owncloud/ocis-proxy/issues/44

**Comment by jnweiger** [comment]
thanks for bringing up the proxy topic. We can continue that as suggested in https://github.com/owncloud/ocis-proxy/issues/44  and close here.

**Pull request merged**
