### PR TITLE
Add ocis to compose playground

### PR DESCRIPTION
**Pull request by micbar**
# compose-playground for ocis

This repository provides different docker-compose yaml files acting as various "infrastructure components".

The aim of these components is, to provide an easy way of setting up owncloud with different infrastrucutre scenarions.

For example, we want to run a *ocis* combined with *redis*.
This could be done by using the following `docker-compose` statement:

```bash
docker-compose \
    -f ocis.yml \
    -f ../cache/redis-ocis.yml \
    up
```

### CODE REVIEW

**Review by xoxys — APPROVED** [review]
LGTM

**Comment by michaelstingl** [comment]
Yeah, works very nice for me!! 😍 

```
git clone https://github.com/owncloud-docker/compose-playground.git

cd compose-playground/ocis

sed -i -e 's/your-url/192.168.103.195/g' config/identifier-registration.yml

cat << EOF > .env
OCIS_BASE_URL=192.168.103.195
OCIS_HTTP_PORT=9200
OCIS_DOCKER_TAG=latest
EOF

docker-compose -f ocis.yml -f ../cache/redis-ocis.yml up -d

curl -k https://192.168.103.195:9200/status.php
```

**Comment by micbar** [comment]
@michaelstingl I also added the trailing slashes in the config/identifier-registration.yml
This is needed to fix the logout issue

**Comment by jnweiger** [comment]
Trying like this:

```
git clone https://github.com/owncloud-docker/compose-playground.git
cd compose-playground/compose/ocis

hostname -I
# -> 78.46.129.60 172.17.0.1 2a01:4f8:c17:2d7::1 
IPADDR=$(hostname -I | sed -e 's/ .*//')   # pick first address from the list

sed -i -e "s/your-url/$IPADDR/g" config/identifier-registration.yml

cat << EOF > .env
OCIS_BASE_URL=$IPADDR
OCIS_HTTP_PORT=9200
OCIS_DOCKER_TAG=latest
EOF

docker-compose -f ocis.yml -f ../cache/redis-ocis.yml up -d

curl -k https://$IPADDR:9200/status.php
```

This setup works for me. But I don't know what credentials should work. admin admin does not.
@michaelstingl  should my real-world kopano credentials work?
@micbar where exactly do I need a trailing slash? From looking at the yml, I fail to spot the correct location.

**Comment by michaelstingl** [comment]
> @michaelstingl Will this work with dummy accounts, like admin-admin?

@jnweiger credentials here:
https://owncloud.github.io/ocis/getting-started/#quickstart-for-developers

```
einstein:relativity
marie:radioactivity
feynman:superfluidity
```

**Comment by michaelstingl** [comment]
> @micbar where exactly do I need a trailing slash? From looking at the yml, I fail to spot the correct location.

@jnweiger as I remember, trailing slashes were needed for the redirect URL's, probably here:
https://github.com/owncloud/ocis-konnectd/blob/master/assets/identifier-registration.yaml

**Comment by jnweiger** [comment]
With user einstein we get
image
OK
When clicking the "Allow" button thus follows:
image
BAD

With user marie or user feynman, the 'Allow' button forwards me to the web view of their owncloud folder. OK.

When I mistype einstein's pasword, I don't get to the `Allow` screen. I get a proper error message. OK.

**Comment by jnweiger** [comment]
> > @micbar where exactly do I need a trailing slash? From looking at the yml, I fail to spot the correct location.
> 
> @jnweiger as I remember, trailing slashes were needed for the redirect URL's, probably here:
> https://github.com/owncloud/ocis-konnectd/blob/master/assets/identifier-registration.yaml

Thanks. Then I think the trailing slashes are already done: https://github.com/owncloud-docker/compose-playground/commit/80367555185b3f2ea5ef374c9e18c6db3067b2f0
OK.

**Comment by michaelstingl** [comment]
> When clicking the "Allow" button thus follows:
> image
> BAD

Please open a new oCIS issue.

**Pull request merged**
